name: aidl-project
channels:
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.1
  - python=3.8
  - numpy=1.21.5
  - openpyxl=3.0.9
  - setuptools=60.0.3
  - matplotlib=3.5.1
  - pandas=1.3.5
  - pillow=8.4.0
  - ray=1.9.2
  - scikit-learn=1.0.1
  - scipy=1.7.3
  - pytorch=1.8.1
  - torch-tb-profiler=0.3.1
  - torchaudio=0.8.1
  - torchvision=0.9.1
